import { writeTextFile } from '../utils/fileWriter';
import { getDefaultSettings } from '../config/settings';

export async function generateContractReadme(contractName: string, contractPath: string): Promise<void> {
  const settings = getDefaultSettings();
  if (!settings.generateReadme) return;

  const readmeContent = generateReadmeContent(contractName, contractPath);
  await writeTextFile(`${contractName}.md`, readmeContent, 'contracts');
}

function generateReadmeContent(contractName: string, contractPath: string): string {
  const settings = getDefaultSettings();
  
  return `# ${contractName}

## Overview

This contract was generated using RetroC - Solidity Smart Contract Generator.

**Contract Path:** \`${contractPath}\`

## Features

- Generated with RetroC extension
- Built on OpenZeppelin Contracts v${settings.openZeppelinVersion}
- Solidity Version: ${settings.defaultSolidityVersion}

## Configuration

${settings.includeReentrancyGuard ? '- ✅ ReentrancyGuard enabled' : '- ❌ ReentrancyGuard disabled'}
${settings.includePausable ? '- ✅ Pausable enabled' : '- ❌ Pausable disabled'}
${settings.includeAccessControl ? '- ✅ AccessControl enabled' : '- ❌ AccessControl disabled'}
${settings.enableGasOptimizations ? '- ✅ Gas optimizations enabled' : '- ❌ Gas optimizations disabled'}
${settings.includeNatSpec ? '- ✅ NatSpec documentation included' : '- ❌ NatSpec documentation not included'}

## Testing

${settings.autoGenerateTests 
  ? `Tests are configured for ${settings.testFramework} framework${settings.useTypeScript ? ' (TypeScript)' : ''}.` 
  : 'Auto-test generation is disabled.'}

## Deployment

${settings.deploymentScripts 
  ? 'A deployment script has been generated in the scripts directory.' 
  : 'Deployment scripts are not auto-generated. Create your own deployment script.'}

## License

${settings.defaultLicense}

---

*Generated by [RetroC](https://github.com/VishalNandy17/RetroC) - Retro Contracts, Modern Speed* ⚡
`;
}


